# Generated by Django 3.1.2 on 2020-10-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='photo',
            field=models.ImageField(blank=True, height_field=30, null=True, upload_to='images/', width_field=15),
        ),
    ]
