# Generated by Django 3.1.2 on 2020-10-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_auto_20201006_2240'),
        ('movies', '0002_auto_20201006_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, to='actors.Actor'),
        ),
    ]
