# Generated by Django 3.1.2 on 2020-10-11 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20201011_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='instructions',
        ),
    ]
